apiVersion: apps/v1
kind: Deployment
metadata:
  name: docmgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docmgr
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: docmgr
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: docmgr
        image: rsrini1983/doc-mgr:1.0
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: 10.10.0.100
