kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "netapp-anf-perf-standard"
  resources:
    requests:
      storage: 100Gi
